name: test

on:
  pull_request:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - docs/**
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - docs/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test ./...
